/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adamasmaca;
import java.io.File;
import java.io.FileWriter;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author alp__
 */
public class SifreEkrani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SifreEkrani.class.getName());

    int denemeSayisi = 0;
    String sifreDosyaYolu = "C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
    String logDosyaYolu = "C:\\P2Oyun\\TXTDosyalar\\log.txt";

    private void logYaz(String islem) {
        try {
            java.time.LocalDateTime simdi = java.time.LocalDateTime.now();
            java.time.format.DateTimeFormatter format = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String tarihSaat = simdi.format(format);
            String logMesaji = tarihSaat + " -> " + islem + "\n";
            FileWriter fw = new FileWriter(logDosyaYolu, true);
            fw.write(logMesaji);
            fw.close();
        } catch (Exception e) {
            System.out.println("Log dosyasına yazılamadı: " + e.getMessage());
        }
    }
    /**
     * Creates new form SifreEkrani
     */
    public SifreEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();
        lblMesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Şifre:");

        txtSifre.addActionListener(this::txtSifreActionPerformed);

        btnGiris.setText("Giriş Yap");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMesaj)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnGiris)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiris))
                .addGap(56, 56, 56)
                .addComponent(lblMesaj)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifreActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        String girilenSifre = new String(txtSifre.getPassword());

        if (girilenSifre.isEmpty()) {
            lblMesaj.setText("Lütfen şifre girin!");
            return;
        }

        File sifreDosyasi = new File(sifreDosyaYolu);

        try {
            if (!sifreDosyasi.exists()) {
                FileWriter fw = new FileWriter(sifreDosyaYolu, true);
                fw.write(girilenSifre);
                fw.close();
                logYaz("İlk şifre oluşturuldu.");
                lblMesaj.setText("Şifre kaydedildi.");
                
                AnaOyunEkrani anaEkran = new AnaOyunEkrani();
                anaEkran.setVisible(true);
                this.dispose(); 
                
            } else {
                Path filePath = sifreDosyasi.toPath();
                List<String> satirlar = Files.readAllLines(filePath, Charset.defaultCharset());
                String kayitliSifre = satirlar.get(0);
                
                if (girilenSifre.equals(kayitliSifre)) {
                    logYaz("Başarılı giriş.");
                    AnaOyunEkrani anaEkran = new AnaOyunEkrani();
                    anaEkran.setVisible(true);
                    this.dispose();
                } else {
                    denemeSayisi++;
                    logYaz("Hatalı giriş denemesi: " + denemeSayisi);
                    if (denemeSayisi >= 3) {
                        JOptionPane.showMessageDialog(this, "3 Kez Hatalı Giriş!");
                        System.exit(0);
                    } else {
                        lblMesaj.setText("Kalan hak: " + (3 - denemeSayisi));
                        txtSifre.setText("");
                    }
                }
            }
        } catch (Exception ex) {
            lblMesaj.setText("Hata!");
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SifreEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMesaj;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
